# Generated by Django 3.1.7 on 2021-04-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
