# Generated by Django 3.1.7 on 2021-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_session_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
