# Generated by Django 3.1.7 on 2021-04-02 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_auto_20210402_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
