# Generated by Django 3.1.7 on 2021-04-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0004_auto_20210402_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='ended_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='started_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
